name = "insightreel-backend"
main = "server/index.js"
compatibility_date = "2024-01-01"

[vars]
# Production 환경변수
PORT = "3000"
USE_GEMINI = "true"
USE_MONGODB = "true"
LOG_LEVEL = "warn"
DISABLE_SHEETS_SAVING = "true"
GEMINI_FALLBACK_MODE = "single-model"
GEMINI_SINGLE_MODEL = "gemini-2.5-flash-lite"

# Build configuration
[build]
command = "npm run build"

# Routes (zone_name 또는 zone_id 필수)
[[routes]]
pattern = "dev.j082175.com/*"
zone_name = "j082175.com"
