const { chromium } = require('playwright');
const fs = require('fs');
const path = require('path');

async function extractInstagramCookies() {
    console.log('🤖 Playwright로 Instagram 쿠키 추출 시작...');

    const browser = await chromium.launch({
        headless: false, // 로그인 과정을 보기 위해 브라우저를 표시
        slowMo: 1000    // 각 동작 사이에 1초 지연
    });

    const context = await browser.newContext({
        userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
    });

    const page = await context.newPage();

    try {
        // Instagram 로그인 페이지로 이동
        console.log('📸 Instagram 로그인 페이지 이동...');
        await page.goto('https://www.instagram.com/accounts/login/', {
            waitUntil: 'networkidle'
        });

        // 로그인 정보 입력
        console.log('🔑 로그인 정보 입력...');
        await page.fill('input[name="username"]', 'j082175j082172@gmail.com');
        await page.fill('input[name="password"]', '!@tkadnjsth3');

        // 로그인 버튼 클릭
        console.log('👆 로그인 버튼 클릭...');
        await page.click('button[type="submit"]');

        // 로그인 완료 대기 (홈페이지 로드 확인)
        console.log('⏳ 로그인 완료 대기...');
        await page.waitForURL('https://www.instagram.com/', {
            timeout: 30000
        });

        console.log('✅ 로그인 성공!');

        // 2FA 또는 추가 확인이 있는 경우 사용자 입력 대기
        const currentUrl = page.url();
        if (currentUrl.includes('challenge') || currentUrl.includes('accounts/onetap')) {
            console.log('🔐 추가 인증이 필요합니다. 브라우저에서 완료해주세요...');
            console.log('완료되면 아무 키나 누르세요.');

            // 사용자 입력 대기
            process.stdin.setRawMode(true);
            process.stdin.resume();
            await new Promise(resolve => process.stdin.once('data', resolve));
            process.stdin.setRawMode(false);
            process.stdin.pause();
        }

        // 쿠키 추출
        console.log('🍪 쿠키 추출 중...');
        const cookies = await context.cookies();

        // Netscape 형식으로 쿠키 파일 생성
        const cookieLines = [
            '# Netscape HTTP Cookie File',
            '# Generated by Instagram Cookie Extractor'
        ];

        cookies.forEach(cookie => {
            if (cookie.domain.includes('instagram.com')) {
                const line = [
                    cookie.domain,
                    cookie.domain.startsWith('.') ? 'TRUE' : 'FALSE',
                    cookie.path,
                    cookie.secure ? 'TRUE' : 'FALSE',
                    Math.floor(cookie.expires || Date.now() / 1000 + 86400 * 30), // 30일 후 만료
                    cookie.name,
                    cookie.value
                ].join('\t');
                cookieLines.push(line);
            }
        });

        // 쿠키 파일 저장
        const cookieFilePath = path.join(__dirname, '../../data/instagram_cookies.txt');
        fs.writeFileSync(cookieFilePath, cookieLines.join('\n'));

        console.log(`✅ 쿠키 파일 저장 완료: ${cookieFilePath}`);
        console.log(`📊 추출된 쿠키 수: ${cookies.filter(c => c.domain.includes('instagram.com')).length}개`);

        // 중요한 쿠키들 확인
        const importantCookies = ['sessionid', 'csrftoken', 'mid', 'ig_did'];
        importantCookies.forEach(cookieName => {
            const cookie = cookies.find(c => c.name === cookieName && c.domain.includes('instagram.com'));
            if (cookie) {
                console.log(`✅ ${cookieName}: 존재`);
            } else {
                console.log(`❌ ${cookieName}: 없음`);
            }
        });

    } catch (error) {
        console.error('❌ 쿠키 추출 실패:', error.message);

        // 스크린샷 저장 (디버깅용)
        await page.screenshot({
            path: path.join(__dirname, '../../data/instagram_error.png')
        });

    } finally {
        console.log('🔚 브라우저 종료...');
        await browser.close();
    }
}

// 스크립트 실행
if (require.main === module) {
    extractInstagramCookies()
        .then(() => {
            console.log('🎉 Instagram 쿠키 추출 완료!');
            process.exit(0);
        })
        .catch(error => {
            console.error('💥 쿠키 추출 실패:', error);
            process.exit(1);
        });
}

module.exports = { extractInstagramCookies };